# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # ...
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: docfx-material/docs/docfx.json

    # Publish generated site using GitHub Pages
    - name: Deploy Netlify
      uses: danakim/gh-action-deploy-netlify@master
      with:
        AUTH_TOKEN: '5e63d94fdfbed0ae8b4e6cf7a0c8d35f4d2c0394d45ff8ee89f0eeca4925020e'
        SITE_ID: '47ea137e-4494-49ae-9ea8-e8a5d4e37470'
        DEPLOY_PROD: true
